# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marinos Agapiou
title: Full Stack Software Engineer
email: marinosagap@outlook.com

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: linkedin
  icon: fab fa-linkedin
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Marinos and I'm a Full Stack Software Engineer with a passion for developing scalable SPA as well as microservice software solutions.
  Passionate about developing clean modular code and excited to be part of a strong development team. I excel in the dynamic realm of software, adept at swiftly adapting and constantly seeking opportunities to learn from my peers, while also sharing my knowledge with others. Fluent in Greek and English, and have a basic understanding of German
  I am mostly skilled in&#58; <mark>Java Spring Boot</mark> and <mark>Angular</mark>.
  My entire skillset includes&#58; Java, JPA, Spring Boot, Maven, NPM, Nodejs, Angular, HTML, CSS, TailwindCSS, Bootstrap, OWASP, PostgreSQL, MongoDB, Docker, Microservices, Jenkins CI/CD, Postman, Git, Github, Gitlab & Azure.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Netcompany-Intrasoft
        link: https://netcompany.com
        # link_text: boringcompany.com
        sub_title: Full Stack Software Engineer
        caption: December 2022 - Present
        # quote: >
        #   Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot, leveraging Azure CI/CD Pipeline.
        description: | # this will include new lines to allow paragraphs
           Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot.
      - layout: left
        title: CENSUS SA
        link: https://census-labs.com
        # link_text: boringcompany.com
        sub_title: IT Security Engineering Intern

        caption: Jan - April 2019
        # quote: >
        #   Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot, leveraging Azure CI/CD Pipeline.
        description: | # this will include new lines to allow paragraphs
           Conducting hands-on penetration testing encompassing Web and Mobile applications as well as Cloud environments, with a specific emphasis on leveraging OWASP security practices, BURP Suite, and sophisticated Python scripting..
      - layout: left
        title: Upstream
        link: https://upstreamsystems.com
        # link_text: boringcompany.com
        sub_title: Software Engineer

        caption: May - Sept 2018
        # quote: >
        #   Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot, leveraging Azure CI/CD Pipeline.
        description: | # this will include new lines to allow paragraphs
           Contributing to the Web Recruitment platform that serves millions of users daily. Utilized technologies like PHP, PL/SQL, and Java Spring Boot, HTML, CSS. Teamed up with creative minds in UX/UI team, making sure we all worked seamlessly together, crafting captivating landing pages.
      - layout: left
        title: CERN
        link: https://home.cern
        # link_text: boringcompany.com
        sub_title: Summer Intern

        caption: July - Aug 2017
        # quote: >
        #   Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot, leveraging Azure CI/CD Pipeline.
        description: | # this will include new lines to allow paragraphs
          Member of the CERN IT team, I actively contributed to implementing a monitoring tool for the InfiniBand switch cluster and an SNMP Trap server receiver, showcasing skills in Python3.
      - layout: left
        title: Synelixis SA
        link: https://synelixis.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern

        caption: July - Aug 2017
        # quote: >
        #   Implementing scalable microservice architectures and REST APIs using Maven, Java Spring Boot, leveraging Azure CI/CD Pipeline.
        description: | # this will include new lines to allow paragraphs
          Trained on Full Stack Web Development and gained expertise in developing hybrid mobile applications using Ionic-Cordova. Contributed to the development of the home page of Synfield mobile application, showcasing skills in AngularJS, jQuery, CSS, and HTML - title: Projects # Title for the section  layout: list # Type of content section (list/text) 
  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LinkedIn clone
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Implementation of a Web App similar to LinkedIn. Technologies used : Gradle, Java Spring Boot, Rest, Java Spring Security, Swagger, OAuth2 , PostgreSQL, Angular6 ,HTML5 ,Bootstrap.
      - layout: left
        title: Airbnb Mobile App clone
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Airbnb-style Android app for short-term rentals in Android Studio, powered by Maven, Java Spring Boot, REST, OAuth2, Java Observables, and MongoDB leveraging Jenkins CI/CD.
      - layout: left
        title: Small Startup Venture
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Teamed up with a friend to create a job-board web application specifically designed for remote developer positions. Technologies used: Node.js, Express.js, Angular, HTML, TailwindCSS, MongoDB and Jenkins CI/CD hosted on Azure cloud.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left center
        title:  MSc in Business Administration - MBA (GPA&#58; 8.3/10) 
        caption: Sept 2020 - Sept 2022
        sub_title: University of Economics and Business (Athens, Greece)
        #  quote: >
        #    "Main Interests: Management & Entrepreneurship"
        description: | # this will include new lines to allow paragraphs
          Thesis&#58; Determinants of Entrepreneurial Intentions of MBA Students and Graduates
          Main Interests&#58; Management & Entrepreneurship
      - layout: left center
        title: BSc in Informatics and Telecomunications(GPA&#58; 8.5/10 - with Honors)
        caption: Sept 2014 - Sept 2019
        sub_title: National and Kapodistrian University of Athens
        #  quote: >
        #    Main Interests: Management & Entrepreneurship
        description: | # this will include new lines to allow paragraphs
          Main Interests&#58; Web Development & Computer Security.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests and hobbies are&#58;
      - Playing Basketball in a local league in Athens 
      - Going to the Theater
      - Also enjoy playing board games with friends

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
